language: node_js
node_js:
  - "0.10"
before_install:
  - "npm install --global grunt-cli"
after_success:
  - "cat coverage/lcov.info coverage/client/lcov.info | node_modules/coveralls/bin/coveralls.js"
