language: node_js
node_js:
  - "0.10"
before_install:
  - "npm install --global grunt-cli"
after_success:
  - "./node_modules/lcov-result-merger/bin/lcov-result-merger.js 'coverage/**/lcov.info' | node_modules/coveralls/bin/coveralls.js"
